default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: test123
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

development:
  <<: *default
  database: school_art_development

dev:
  <<: *default
  database: school_art_dev

staging:
  <<: *default
  database: school_art_staging

production:
  <<: *default
  database: school_art_production

test: &test
  <<: *default
  database: school_art_test

cucumber:
  <<: *test
